from __future__ import annotations

import argparse
import os
import sqlite3
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipeline_common.refresh_sp500_shared_prices import (  # noqa: E402
    DEFAULT_COMPONENTS_CSV,
    DEFAULT_DATA_DIR,
    DEFAULT_START_DATE,
    DEFAULT_SHARED_DB_ROOT,
    _build_market_cap_frame_from_latest_shares,
    _download_shares_histories,
    _download_symbol_frames,
    _infer_share_histories_from_existing_market_caps,
    _market_cap_wide_to_long,
    _overlay_fresh_on_existing,
    _read_symbol_list,
    _share_histories_to_wide,
    refresh_sp500_shared_prices,
)
from pipeline_common.shared_fundamentals import derive_shared_fundamental_metrics  # noqa: E402
from pipeline_common.shared_sp500_prices_sql import (  # noqa: E402
    _connect_shared_prices_read_db,
    _ensure_postgres_news_context_views,
    shared_prices_database_url,
    shared_prices_sqlite_path,
    using_remote_shared_prices_db,
    using_supabase_shared_prices_db,
)
from pipeline_macro.macro_data_store import (  # noqa: E402
    ALL_SPECS,
    MacroSeriesSpec,
    _connect_macro_read_db,
    macro_database_url,
    macro_db_path,
    normalize_series,
    using_remote_macro_db,
    using_supabase_macro_db,
)
from pipeline_macro.refresh_macro_prices import _load_series  # noqa: E402
from pipeline_common.news_data import fetch_google_news_articles  # noqa: E402
from pipeline_common.refresh_sp500_news import (  # noqa: E402
    DEFAULT_BACKFILL_DAYS,
    DEFAULT_INCREMENTAL_OVERLAP_DAYS,
    DEFAULT_MAX_ITEMS,
    _article_is_in_window,
    _article_query_for_symbol,
    _publish_date_text,
    sync_sp500_news_articles,
)
from pipeline_macro.refresh_macro_prices import refresh_macro_prices  # noqa: E402
from pipeline_common.refresh_shared_quarterly_fundamentals import (  # noqa: E402
    _extract_quarterly_rows,
    _filter_rows_newer_than_db,
)

try:
    from fredapi import Fred
except Exception:  # pragma: no cover - optional deployment dependency
    Fred = None


@dataclass(frozen=True)
class JobCounts:
    price_rows: int = 0
    fundamental_rows: int = 0
    news_rows: int = 0
    macro_rows: int = 0


def _log(message: str) -> None:
    print(f"[refresh-turso-daily] {message}", flush=True)


def _remote_label() -> str:
    return "Supabase" if (using_supabase_shared_prices_db() or using_supabase_macro_db()) else "Turso"


def _env_first(*names: str) -> str:
    for name in names:
        value = str(os.getenv(name, "")).strip()
        if value:
            return value
    return ""


def _fred_client():
    key = _env_first("FRED_API_KEY")
    if Fred is None or not key:
        return None
    return Fred(api_key=key)


def _is_postgres_conn(conn) -> bool:
    return bool(getattr(conn, "_keumj_remote_postgres", False))


def _ensure_remote_prices_schema(conn) -> None:
    if _is_postgres_conn(conn):
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS prices (
                symbol TEXT NOT NULL,
                date TEXT NOT NULL,
                open DOUBLE PRECISION NOT NULL,
                high DOUBLE PRECISION NOT NULL,
                low DOUBLE PRECISION NOT NULL,
                close DOUBLE PRECISION NOT NULL,
                volume DOUBLE PRECISION NOT NULL DEFAULT 0,
                adj_close DOUBLE PRECISION,
                dividends DOUBLE PRECISION NOT NULL DEFAULT 0,
                stock_splits DOUBLE PRECISION NOT NULL DEFAULT 0,
                market_cap DOUBLE PRECISION,
                PRIMARY KEY (symbol, date)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS news_articles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL,
                publish_date TIMESTAMPTZ NOT NULL,
                title TEXT NOT NULL,
                link TEXT NOT NULL,
                source TEXT NOT NULL,
                sentiment_score DOUBLE PRECISION,
                analysis_status TEXT NOT NULL DEFAULT 'pending'
            )
            """
        )
        _ensure_postgres_news_article_ids(conn)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS fundamentals_snapshot (
                symbol TEXT PRIMARY KEY,
                as_of_date TEXT NOT NULL,
                roe DOUBLE PRECISION,
                per DOUBLE PRECISION,
                pbr DOUBLE PRECISION,
                source TEXT NOT NULL DEFAULT 'unknown',
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS fundamentals_quarterly (
                symbol TEXT NOT NULL,
                fiscal_date TEXT NOT NULL,
                filing_date TEXT,
                period_type TEXT NOT NULL DEFAULT 'quarterly',
                net_income DOUBLE PRECISION,
                diluted_eps DOUBLE PRECISION,
                stockholders_equity DOUBLE PRECISION,
                total_assets DOUBLE PRECISION,
                total_debt DOUBLE PRECISION,
                current_assets DOUBLE PRECISION,
                current_liabilities DOUBLE PRECISION,
                operating_cash_flow DOUBLE PRECISION,
                free_cash_flow DOUBLE PRECISION,
                source TEXT NOT NULL DEFAULT 'unknown',
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (symbol, fiscal_date)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS refresh_runs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_name TEXT NOT NULL,
                mode TEXT NOT NULL,
                status TEXT NOT NULL,
                started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                finished_at TIMESTAMPTZ,
                price_rows INTEGER NOT NULL DEFAULT 0,
                fundamental_rows INTEGER NOT NULL DEFAULT 0,
                news_rows INTEGER NOT NULL DEFAULT 0,
                macro_rows INTEGER NOT NULL DEFAULT 0,
                message TEXT NOT NULL DEFAULT ''
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_prices_symbol_date ON prices(symbol, date)")
        _ensure_postgres_unique_index(conn, "prices", ("symbol", "date"), "ux_prices_symbol_date")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_prices_date ON prices(date)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_snapshot_as_of_date ON fundamentals_snapshot(as_of_date)")
        _ensure_postgres_unique_index(conn, "fundamentals_snapshot", ("symbol",), "ux_fundamentals_snapshot_symbol")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_quarterly_symbol_fiscal_date ON fundamentals_quarterly(symbol, fiscal_date)")
        _ensure_postgres_unique_index(
            conn,
            "fundamentals_quarterly",
            ("symbol", "fiscal_date"),
            "ux_fundamentals_quarterly_symbol_fiscal_date",
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_quarterly_fiscal_date ON fundamentals_quarterly(fiscal_date)")
        _ensure_postgres_news_context_views(conn)
        conn.commit()
        return
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS prices (
            symbol TEXT NOT NULL,
            date TEXT NOT NULL,
            open REAL NOT NULL,
            high REAL NOT NULL,
            low REAL NOT NULL,
            close REAL NOT NULL,
            volume REAL NOT NULL DEFAULT 0,
            adj_close REAL,
            dividends REAL NOT NULL DEFAULT 0,
            stock_splits REAL NOT NULL DEFAULT 0,
            market_cap REAL,
            PRIMARY KEY (symbol, date)
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_prices_symbol_date ON prices(symbol, date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_prices_date ON prices(date)")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS news_articles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ticker TEXT NOT NULL,
            publish_date DATETIME NOT NULL,
            title TEXT NOT NULL,
            link TEXT NOT NULL,
            source TEXT NOT NULL,
            sentiment_score REAL,
            analysis_status TEXT NOT NULL DEFAULT 'pending'
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS fundamentals_snapshot (
            symbol TEXT PRIMARY KEY,
            as_of_date TEXT NOT NULL,
            roe REAL,
            per REAL,
            pbr REAL,
            source TEXT NOT NULL DEFAULT 'unknown',
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS fundamentals_quarterly (
            symbol TEXT NOT NULL,
            fiscal_date TEXT NOT NULL,
            filing_date TEXT,
            period_type TEXT NOT NULL DEFAULT 'quarterly',
            net_income REAL,
            diluted_eps REAL,
            stockholders_equity REAL,
            total_assets REAL,
            total_debt REAL,
            current_assets REAL,
            current_liabilities REAL,
            operating_cash_flow REAL,
            free_cash_flow REAL,
            source TEXT NOT NULL DEFAULT 'unknown',
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (symbol, fiscal_date)
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_ticker_publish_date ON news_articles(ticker, publish_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_publish_date ON news_articles(publish_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_ticker_publish_day ON news_articles(ticker, date(publish_date))")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_analysis_status_publish_date ON news_articles(analysis_status, publish_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_snapshot_as_of_date ON fundamentals_snapshot(as_of_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_quarterly_symbol_fiscal_date ON fundamentals_quarterly(symbol, fiscal_date)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_fundamentals_quarterly_fiscal_date ON fundamentals_quarterly(fiscal_date)")
    conn.execute(
        """
        CREATE VIEW IF NOT EXISTS news_articles_price_context AS
        SELECT
            n.id,
            n.ticker,
            n.publish_date,
            date(n.publish_date) AS publish_day,
            n.title,
            n.link,
            n.source,
            n.sentiment_score,
            n.analysis_status,
            p.date AS price_date,
            p.open,
            p.high,
            p.low,
            p.close,
            p.adj_close,
            p.volume,
            p.market_cap
        FROM news_articles AS n
        LEFT JOIN prices AS p
            ON p.symbol = n.ticker
           AND p.date = date(n.publish_date)
        """
    )
    conn.execute(
        """
        CREATE VIEW IF NOT EXISTS news_articles_market_context AS
        SELECT
            n.id,
            n.ticker,
            n.publish_date,
            date(n.publish_date) AS publish_day,
            n.title,
            n.link,
            n.source,
            n.sentiment_score,
            n.analysis_status,
            p.date AS reference_price_date,
            CASE
                WHEN p.date = date(n.publish_date) THEN 1
                ELSE 0
            END AS matched_on_publish_day,
            p.open,
            p.high,
            p.low,
            p.close,
            p.adj_close,
            p.volume,
            p.market_cap
        FROM news_articles AS n
        LEFT JOIN prices AS p
            ON p.symbol = n.ticker
           AND p.date = (
                SELECT MAX(p2.date)
                FROM prices AS p2
                WHERE p2.symbol = n.ticker
                  AND p2.date <= date(n.publish_date)
           )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS refresh_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            job_name TEXT NOT NULL,
            mode TEXT NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TEXT,
            price_rows INTEGER NOT NULL DEFAULT 0,
            fundamental_rows INTEGER NOT NULL DEFAULT 0,
            news_rows INTEGER NOT NULL DEFAULT 0,
            macro_rows INTEGER NOT NULL DEFAULT 0,
            message TEXT NOT NULL DEFAULT ''
        )
        """
    )
    _ensure_refresh_run_columns(conn)
    conn.commit()


def _ensure_remote_macro_schema(conn) -> None:
    if _is_postgres_conn(conn):
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS macro_series (
                series_id TEXT NOT NULL,
                date TEXT NOT NULL,
                value DOUBLE PRECISION NOT NULL,
                dataset TEXT NOT NULL,
                frequency TEXT NOT NULL,
                source TEXT NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (series_id, date)
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_macro_series_date ON macro_series(date)")
        _ensure_postgres_unique_index(conn, "macro_series", ("series_id", "date"), "ux_macro_series_series_id_date")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS macro_metadata (
                series_id TEXT PRIMARY KEY,
                dataset TEXT NOT NULL,
                frequency TEXT NOT NULL,
                source TEXT NOT NULL,
                min_date TEXT,
                max_date TEXT,
                row_count INTEGER NOT NULL DEFAULT 0,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        _ensure_postgres_unique_index(conn, "macro_metadata", ("series_id",), "ux_macro_metadata_series_id")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS refresh_runs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_name TEXT NOT NULL,
                mode TEXT NOT NULL,
                status TEXT NOT NULL,
                started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                finished_at TIMESTAMPTZ,
                price_rows INTEGER NOT NULL DEFAULT 0,
                fundamental_rows INTEGER NOT NULL DEFAULT 0,
                news_rows INTEGER NOT NULL DEFAULT 0,
                macro_rows INTEGER NOT NULL DEFAULT 0,
                message TEXT NOT NULL DEFAULT ''
            )
            """
        )
        conn.commit()
        return
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS macro_series (
            series_id TEXT NOT NULL,
            date TEXT NOT NULL,
            value REAL NOT NULL,
            dataset TEXT NOT NULL,
            frequency TEXT NOT NULL,
            source TEXT NOT NULL,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (series_id, date)
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_macro_series_date ON macro_series(date)")
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS macro_metadata (
            series_id TEXT PRIMARY KEY,
            dataset TEXT NOT NULL,
            frequency TEXT NOT NULL,
            source TEXT NOT NULL,
            min_date TEXT,
            max_date TEXT,
            row_count INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS refresh_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            job_name TEXT NOT NULL,
            mode TEXT NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TEXT,
            price_rows INTEGER NOT NULL DEFAULT 0,
            fundamental_rows INTEGER NOT NULL DEFAULT 0,
            news_rows INTEGER NOT NULL DEFAULT 0,
            macro_rows INTEGER NOT NULL DEFAULT 0,
            message TEXT NOT NULL DEFAULT ''
        )
        """
    )
    _ensure_refresh_run_columns(conn)
    conn.commit()


def _ensure_postgres_news_article_ids(conn) -> None:
    if not _is_postgres_conn(conn):
        return
    conn.execute("CREATE SEQUENCE IF NOT EXISTS news_articles_id_seq")
    conn.execute(
        """
        SELECT setval(
            'news_articles_id_seq',
            GREATEST(COALESCE((SELECT MAX(id) FROM news_articles), 0), 1),
            COALESCE((SELECT MAX(id) FROM news_articles), 0) > 0
        )
        """
    )
    conn.execute("UPDATE news_articles SET id = nextval('news_articles_id_seq') WHERE id IS NULL")
    conn.execute(
        """
        SELECT setval(
            'news_articles_id_seq',
            GREATEST(COALESCE((SELECT MAX(id) FROM news_articles), 0), 1),
            COALESCE((SELECT MAX(id) FROM news_articles), 0) > 0
        )
        """
    )
    conn.execute("ALTER TABLE news_articles ALTER COLUMN id SET DEFAULT nextval('news_articles_id_seq')")
    conn.execute("ALTER SEQUENCE news_articles_id_seq OWNED BY news_articles.id")
    _ensure_postgres_unique_index(conn, "news_articles", ("id",), "ux_news_articles_id")


def _ensure_postgres_unique_index(conn, table: str, columns: tuple[str, ...], index_name: str) -> None:
    if not _is_postgres_conn(conn):
        return
    quoted_columns = ", ".join(columns)
    equality_sql = " AND ".join(f"older.{col} = newer.{col}" for col in columns)
    conn.execute(
        f"""
        DELETE FROM {table} AS older
        USING {table} AS newer
        WHERE older.ctid < newer.ctid
          AND {equality_sql}
        """
    )
    conn.execute(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS {index_name}
        ON {table}({quoted_columns})
        """
    )


def _ensure_refresh_run_columns(conn) -> None:
    if _is_postgres_conn(conn):
        return
    cols = {str(row[1]).strip().lower() for row in conn.execute("PRAGMA table_info(refresh_runs)").fetchall()}
    if "fundamental_rows" not in cols:
        conn.execute("ALTER TABLE refresh_runs ADD COLUMN fundamental_rows INTEGER NOT NULL DEFAULT 0")
    if "news_rows" not in cols:
        conn.execute("ALTER TABLE refresh_runs ADD COLUMN news_rows INTEGER NOT NULL DEFAULT 0")


def _table_max_date(conn, table: str, *, where_sql: str = "", params: tuple[object, ...] = ()) -> str | None:
    return _table_max_value(conn, table, "date", where_sql=where_sql, params=params)


def _table_max_value(
    conn,
    table: str,
    column: str,
    *,
    where_sql: str = "",
    params: tuple[object, ...] = (),
) -> str | None:
    query = f"SELECT MAX({column}) FROM {table}"
    if where_sql:
        query += f" WHERE {where_sql}"
    row = conn.execute(query, params).fetchone()
    value = row[0] if row else None
    return str(value) if value else None


def _overlap_fetch_start_date(default_start_date: str, max_date: str | None, overlap_days: int) -> str:
    if not max_date:
        return pd.Timestamp(default_start_date).normalize().strftime("%Y-%m-%d")
    try:
        overlapped = pd.Timestamp(max_date).normalize() - pd.Timedelta(days=max(int(overlap_days), 0))
    except Exception:
        return pd.Timestamp(default_start_date).normalize().strftime("%Y-%m-%d")
    return max(pd.Timestamp(default_start_date).normalize(), overlapped).strftime("%Y-%m-%d")


def _price_rows_from_frames(frames: dict[str, pd.DataFrame], *, only_after: str | None) -> list[tuple[object, ...]]:
    cutoff = pd.Timestamp(only_after).normalize() if only_after else None
    rows: list[tuple[object, ...]] = []
    for symbol, frame in frames.items():
        if frame is None or frame.empty:
            continue
        clean = frame.copy()
        clean.index = pd.to_datetime(clean.index, errors="coerce").normalize()
        clean = clean[~clean.index.isna()].sort_index()
        if cutoff is not None:
            clean = clean[clean.index > cutoff]
        required = ["open", "high", "low", "close"]
        if clean.empty or any(col not in clean.columns for col in required):
            continue
        if "volume" not in clean.columns:
            clean["volume"] = 0.0
        if "adj_close" not in clean.columns:
            clean["adj_close"] = clean["close"]
        if "dividends" not in clean.columns:
            clean["dividends"] = 0.0
        if "stock_splits" not in clean.columns:
            clean["stock_splits"] = 0.0
        for idx, row in clean.iterrows():
            values = [row.get(col) for col in required]
            if any(pd.isna(value) for value in values):
                continue
            rows.append(
                (
                    str(symbol).strip().upper(),
                    pd.Timestamp(idx).strftime("%Y-%m-%d"),
                    float(row["open"]),
                    float(row["high"]),
                    float(row["low"]),
                    float(row["close"]),
                    float(row.get("volume", 0.0) or 0.0),
                    float(row["adj_close"]) if pd.notna(row.get("adj_close")) else float(row["close"]),
                    float(row.get("dividends", 0.0) or 0.0),
                    float(row.get("stock_splits", 0.0) or 0.0),
                )
            )
    return rows


def _insert_price_rows(conn, rows: list[tuple[object, ...]], *, chunk_size: int = 1000) -> int:
    if not rows:
        return 0
    if _is_postgres_conn(conn):
        sql = """
            INSERT INTO prices
            (symbol, date, open, high, low, close, volume, adj_close, dividends, stock_splits)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(symbol, date) DO NOTHING
        """
    else:
        sql = """
            INSERT OR IGNORE INTO prices
            (symbol, date, open, high, low, close, volume, adj_close, dividends, stock_splits)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
    for i in range(0, len(rows), max(int(chunk_size), 1)):
        conn.executemany(sql, rows[i : i + max(int(chunk_size), 1)])
    conn.commit()
    return len(rows)


def _frames_to_close_metrics_wide(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    parts: list[pd.Series] = []
    for symbol, frame in frames.items():
        if frame is None or frame.empty or "Close" not in frame.columns:
            continue
        clean = frame.copy()
        clean.index = pd.to_datetime(clean.index, errors="coerce").normalize()
        clean = clean[~clean.index.isna()].sort_index()
        close = pd.to_numeric(clean["Close"], errors="coerce").dropna()
        if close.empty:
            continue
        parts.append(close.rename(f"{str(symbol).strip().upper()}_Close"))
    if not parts:
        return pd.DataFrame()
    out = pd.concat(parts, axis=1).sort_index()
    out.index = pd.to_datetime(out.index, errors="coerce").normalize()
    out = out[~out.index.isna()]
    return out.dropna(how="all")


def _existing_market_caps_wide(conn, *, start_date: str) -> pd.DataFrame:
    try:
        rows = conn.execute(
            """
            SELECT symbol, date, market_cap
            FROM prices
            WHERE market_cap IS NOT NULL
              AND date >= ?
            ORDER BY date, symbol
            """,
            (start_date,),
        ).fetchall()
    except Exception as exc:
        _log(f"S&P500 market cap fallback read skipped: {type(exc).__name__}: {exc}")
        return pd.DataFrame()
    if not rows:
        return pd.DataFrame()

    frame = pd.DataFrame(rows, columns=["symbol", "date", "market_cap"])
    frame["symbol"] = frame["symbol"].astype(str).str.strip().str.upper()
    frame["date"] = pd.to_datetime(frame["date"], errors="coerce").dt.normalize()
    frame["market_cap"] = pd.to_numeric(frame["market_cap"], errors="coerce")
    frame = frame.dropna(subset=["symbol", "date", "market_cap"])
    if frame.empty:
        return pd.DataFrame()
    wide = frame.pivot_table(index="date", columns="symbol", values="market_cap", aggfunc="last")
    wide = wide.sort_index()
    wide.index = pd.to_datetime(wide.index, errors="coerce").normalize()
    wide = wide[~wide.index.isna()]
    wide = wide[~wide.index.duplicated(keep="last")]
    return wide.dropna(how="all")


def _update_market_caps_direct(
    conn,
    *,
    symbols: list[str],
    frames: dict[str, pd.DataFrame],
    fetch_start: str,
    end_date: str,
    chunk_size: int,
    provider: str,
    pause_seconds: float,
) -> int:
    metrics_df = _frames_to_close_metrics_wide(frames)
    if metrics_df.empty:
        _log("S&P500 market cap direct refresh skipped: no close prices.")
        return 0
    try:
        shares_histories, missing = _download_shares_histories(
            symbols,
            start_date=fetch_start,
            end_date=end_date,
            provider=provider,
            chunk_size=chunk_size,
            pause_seconds=pause_seconds,
        )
    except Exception as exc:
        _log(f"S&P500 market cap direct refresh skipped: {type(exc).__name__}: {exc}")
        return 0
    if missing:
        _log(f"S&P500 market cap missing share histories: {len(missing)}")
    fetched_shares_df = _share_histories_to_wide(shares_histories)
    fallback_start = (pd.Timestamp(fetch_start).normalize() - pd.Timedelta(days=30)).strftime("%Y-%m-%d")
    existing_market_cap_df = _existing_market_caps_wide(conn, start_date=fallback_start)
    inferred_shares_df = _share_histories_to_wide(
        _infer_share_histories_from_existing_market_caps(
            metrics_df,
            existing_market_cap_df,
            symbols,
        )
    )
    if not inferred_shares_df.empty:
        missing_before = set(symbols).difference(fetched_shares_df.columns if not fetched_shares_df.empty else [])
        recovered = sorted(missing_before.intersection(inferred_shares_df.columns))
        if recovered:
            _log(f"S&P500 market cap fallback recovered shares for {len(recovered)} symbols from existing DB values")
    shares_df = _overlay_fresh_on_existing(fetched_shares_df, inferred_shares_df)
    market_cap_df = _build_market_cap_frame_from_latest_shares(metrics_df, shares_df)
    market_cap_long = _market_cap_wide_to_long(
        market_cap_df,
        only_after=(pd.Timestamp(fetch_start).normalize() - pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
    )
    if market_cap_long.empty:
        _log("S&P500 market cap direct refresh skipped: no candidate rows.")
        return 0
    rows = [
        (float(row.market_cap), str(row.symbol), str(row.date))
        for row in market_cap_long.itertuples(index=False)
        if pd.notna(row.market_cap)
    ]
    attempted = _executemany_chunks(
        conn,
        """
        UPDATE prices
        SET market_cap = ?
        WHERE symbol = ? AND date = ?
        """,
        rows,
    )
    _log(f"S&P500 market cap direct refresh candidate rows={attempted}")
    return attempted


def _remote_has_table(conn, table: str) -> bool:
    if _is_postgres_conn(conn):
        row = conn.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ?",
            (table,),
        ).fetchone()
        return row is not None
    row = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name = ?", (table,)).fetchone()
    return row is not None


def _local_has_table(conn: sqlite3.Connection, table: str) -> bool:
    row = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name = ?", (table,)).fetchone()
    return row is not None


def _executemany_chunks(conn, sql: str, rows: list[tuple[object, ...]], *, chunk_size: int = 1000) -> int:
    if not rows:
        return 0
    size = max(int(chunk_size), 1)
    for i in range(0, len(rows), size):
        conn.executemany(sql, rows[i : i + size])
    conn.commit()
    return len(rows)


def refresh_prices_direct(
    *,
    symbols_csv: Path,
    start_date: str,
    chunk_size: int,
    provider: str,
    pause_seconds: float,
    overlap_days: int,
) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for direct refresh.")
    with _connect_shared_prices_read_db() as conn:
        _ensure_remote_prices_schema(conn)
        old_max_date = _table_max_date(conn, "prices")
        fetch_start = _overlap_fetch_start_date(start_date, old_max_date, overlap_days)
        end_date = (pd.Timestamp.today().normalize() + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
        symbols = _read_symbol_list(symbols_csv, Path("__remote_turso__.sqlite"))
        _log(
            f"S&P500 direct refresh: symbols={len(symbols)} old_max={old_max_date or '-'} "
            f"fetch_start={fetch_start} end_exclusive={end_date}"
        )
        if pd.Timestamp(fetch_start).normalize() >= pd.Timestamp(end_date).normalize():
            _log("S&P500 direct refresh skipped: no new date window.")
            return 0
        frames, missing = _download_symbol_frames(
            symbols,
            start_date=fetch_start,
            end_date=end_date,
            chunk_size=chunk_size,
            provider=provider,
            pause_seconds=pause_seconds,
        )
        if missing:
            _log(f"S&P500 missing symbols: {len(missing)}")
        rows = _price_rows_from_frames(
            frames,
            only_after=(pd.Timestamp(fetch_start).normalize() - pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
        )
        attempted = _insert_price_rows(conn, rows)
        _update_market_caps_direct(
            conn,
            symbols=symbols,
            frames=frames,
            fetch_start=fetch_start,
            end_date=end_date,
            chunk_size=chunk_size,
            provider=provider,
            pause_seconds=pause_seconds,
        )
        _log(f"S&P500 direct refresh wrote candidate rows={attempted}")
        return attempted


def _sp500_symbols(symbols_csv: Path) -> list[str]:
    return _read_symbol_list(symbols_csv, Path("__remote_turso__.sqlite"))


def refresh_fundamentals_direct(*, symbols_csv: Path, limit_per_symbol: int, pause_seconds: float) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for direct fundamentals refresh.")
    symbols = _sp500_symbols(symbols_csv)
    total = 0
    with _connect_shared_prices_read_db() as conn:
        _ensure_remote_prices_schema(conn)
        for idx, symbol in enumerate(symbols, start=1):
            old_max = _table_max_value(
                conn,
                "fundamentals_quarterly",
                "fiscal_date",
                where_sql="symbol = ?",
                params=(symbol,),
            )
            try:
                rows = _extract_quarterly_rows(symbol, limit_per_symbol=limit_per_symbol)
            except Exception as exc:
                _log(f"fundamentals {symbol}: failed {type(exc).__name__}: {exc}")
                continue
            rows_to_store, _ = _filter_rows_newer_than_db(rows, old_max)
            if not rows_to_store:
                continue
            tuples = [
                (
                    row.get("symbol"),
                    row.get("fiscal_date"),
                    row.get("filing_date"),
                    row.get("period_type"),
                    row.get("net_income"),
                    row.get("diluted_eps"),
                    row.get("stockholders_equity"),
                    row.get("total_assets"),
                    row.get("total_debt"),
                    row.get("current_assets"),
                    row.get("current_liabilities"),
                    row.get("operating_cash_flow"),
                    row.get("free_cash_flow"),
                    row.get("source"),
                )
                for row in rows_to_store
            ]
            total += _executemany_chunks(
                conn,
                """
                INSERT INTO fundamentals_quarterly(
                    symbol, fiscal_date, filing_date, period_type, net_income, diluted_eps,
                    stockholders_equity, total_assets, total_debt, current_assets,
                    current_liabilities, operating_cash_flow, free_cash_flow, source
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(symbol, fiscal_date) DO UPDATE SET
                    filing_date=excluded.filing_date,
                    period_type=excluded.period_type,
                    net_income=excluded.net_income,
                    diluted_eps=excluded.diluted_eps,
                    stockholders_equity=excluded.stockholders_equity,
                    total_assets=excluded.total_assets,
                    total_debt=excluded.total_debt,
                    current_assets=excluded.current_assets,
                    current_liabilities=excluded.current_liabilities,
                    operating_cash_flow=excluded.operating_cash_flow,
                    free_cash_flow=excluded.free_cash_flow,
                    source=excluded.source,
                    updated_at=CURRENT_TIMESTAMP
                """,
                tuples,
            )
            if idx % 25 == 0:
                _log(f"fundamentals progress {idx}/{len(symbols)} total_candidate_rows={total}")
            if pause_seconds > 0:
                import time

                time.sleep(float(pause_seconds))
    _log(f"fundamentals direct refresh candidate rows={total}")
    return total


def _sqlite_value(value: object) -> object:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except TypeError:
        return value
    if hasattr(value, "item"):
        return value.item()
    return value


def refresh_fundamentals_snapshot_direct(*, symbols_csv: Path, limit_per_symbol: int) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for direct fundamentals snapshot refresh.")
    symbols = _sp500_symbols(symbols_csv)
    frame, source = derive_shared_fundamental_metrics(
        symbols,
        limit_per_symbol=max(int(limit_per_symbol), 4),
    )
    if frame is None or frame.empty:
        _log("fundamentals_snapshot direct refresh skipped: no derived rows.")
        return 0
    rows = []
    for row in frame.itertuples(index=False):
        data = row._asdict()
        symbol = str(data.get("symbol", "")).strip().upper()
        as_of_date = _sqlite_value(data.get("as_of_date"))
        if not symbol or not as_of_date:
            continue
        rows.append(
            (
                symbol,
                str(as_of_date),
                _sqlite_value(data.get("roe")),
                _sqlite_value(data.get("per")),
                _sqlite_value(data.get("pbr")),
                source or _sqlite_value(data.get("source")) or "turso:derived",
            )
        )
    with _connect_shared_prices_read_db() as conn:
        _ensure_remote_prices_schema(conn)
        attempted = _executemany_chunks(
            conn,
            """
            INSERT INTO fundamentals_snapshot(symbol, as_of_date, roe, per, pbr, source)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(symbol) DO UPDATE SET
                as_of_date=excluded.as_of_date,
                roe=excluded.roe,
                per=excluded.per,
                pbr=excluded.pbr,
                source=excluded.source,
                updated_at=CURRENT_TIMESTAMP
            """,
            rows,
        )
    _log(f"fundamentals_snapshot direct refresh candidate rows={attempted}")
    return attempted


def refresh_news_direct(
    *,
    symbols_csv: Path,
    backfill_days: int,
    overlap_days: int,
    max_items: int,
    timeout: int,
) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for direct news refresh.")
    symbols = _sp500_symbols(symbols_csv)
    run_date = datetime.now().date()
    total = 0
    with _connect_shared_prices_read_db() as conn:
        _ensure_remote_prices_schema(conn)
        max_publish = _table_max_value(conn, "news_articles", "publish_date")
        start_day = run_date - timedelta(days=max(int(backfill_days) - 1, 0))
        if start_day > run_date:
            start_day = run_date
        _log(
            f"news direct refresh: symbols={len(symbols)} max_publish={max_publish or '-'} "
            f"backfill_start_day={start_day} run_date={run_date} max_items={max_items} timeout={timeout} "
            "mode=fixed-backfill-dedup-by-ticker-link"
        )
        for idx, symbol in enumerate(symbols, start=1):
            try:
                articles = fetch_google_news_articles(
                    query=_article_query_for_symbol(symbol),
                    max_items=max_items,
                    timeout=timeout,
                )
            except Exception as exc:
                _log(f"news {symbol}: failed {type(exc).__name__}: {exc}")
                continue
            rows = []
            for article in articles:
                if article.publish_date is None or not _article_is_in_window(article, start_date=start_day, as_of_date=run_date):
                    continue
                rows.append(
                    (
                        symbol,
                        _publish_date_text(article.publish_date),
                        article.title,
                        article.link,
                        article.source,
                        None,
                        "pending",
                        symbol,
                        article.link,
                    )
                )
            total += _executemany_chunks(
                conn,
                """
                INSERT INTO news_articles (ticker, publish_date, title, link, source, sentiment_score, analysis_status)
                SELECT ?, ?, ?, ?, ?, ?, ?
                WHERE NOT EXISTS (
                    SELECT 1 FROM news_articles
                    WHERE ticker = ? AND link = ?
                )
                """,
                rows,
            )
            if idx % 25 == 0:
                _log(f"news progress {idx}/{len(symbols)} total_candidate_rows={total}")
    _log(f"news direct refresh candidate rows={total}")
    return total


def _macro_series_rows(spec: MacroSeriesSpec, series: pd.Series, source: str) -> list[tuple[object, ...]]:
    clean = normalize_series(series, series_id=spec.series_id)
    return [
        (
            spec.series_id,
            pd.Timestamp(idx).strftime("%Y-%m-%d"),
            float(value),
            spec.dataset,
            spec.frequency,
            source,
        )
        for idx, value in clean.items()
    ]


def _upsert_macro_rows(conn, spec: MacroSeriesSpec, rows: list[tuple[object, ...]], source: str) -> int:
    if not rows:
        return 0
    conn.executemany(
        """
        INSERT INTO macro_series (series_id, date, value, dataset, frequency, source, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
        ON CONFLICT(series_id, date) DO UPDATE SET
            value=excluded.value,
            dataset=excluded.dataset,
            frequency=excluded.frequency,
            source=excluded.source,
            updated_at=CURRENT_TIMESTAMP
        """,
        rows,
    )
    conn.execute(
        """
        INSERT INTO macro_metadata (series_id, dataset, frequency, source, min_date, max_date, row_count, updated_at)
        VALUES (
            ?, ?, ?, ?,
            (SELECT MIN(date) FROM macro_series WHERE series_id = ?),
            (SELECT MAX(date) FROM macro_series WHERE series_id = ?),
            (SELECT COUNT(*) FROM macro_series WHERE series_id = ?),
            CURRENT_TIMESTAMP
        )
        ON CONFLICT(series_id) DO UPDATE SET
            dataset=excluded.dataset,
            frequency=excluded.frequency,
            source=excluded.source,
            min_date=excluded.min_date,
            max_date=excluded.max_date,
            row_count=excluded.row_count,
            updated_at=CURRENT_TIMESTAMP
        """,
        (spec.series_id, spec.dataset, spec.frequency, source, spec.series_id, spec.series_id, spec.series_id),
    )
    conn.commit()
    return len(rows)


def _parse_series_ids(value: str) -> set[str]:
    return {part.strip().upper() for part in str(value or "").split(",") if part.strip()}


def refresh_macro_direct(*, default_years: int, rewrite_series: set[str] | None = None) -> int:
    if not using_remote_macro_db():
        raise RuntimeError("KEUMJ_MACRO_DATABASE_URL or KEUMJ_MACRO_SUPABASE_* must be set for direct macro refresh.")
    fred = _fred_client()
    rewrite_ids = {item.upper() for item in rewrite_series or set()}
    total = 0
    with _connect_macro_read_db() as conn:
        _ensure_remote_macro_schema(conn)
        for spec in ALL_SPECS:
            series_id = str(spec.series_id).upper()
            rewrite = series_id in rewrite_ids
            old_max = None if rewrite else _table_max_date(conn, "macro_series", where_sql="series_id = ?", params=(spec.series_id,))
            if rewrite:
                start = (pd.Timestamp.today().normalize() - pd.DateOffset(years=int(default_years))).normalize()
                conn.execute("DELETE FROM macro_series WHERE series_id = ?", (spec.series_id,))
                conn.execute("DELETE FROM macro_metadata WHERE series_id = ?", (spec.series_id,))
                conn.commit()
                _log(f"macro {spec.series_id}: rewriting full {int(default_years)}y window from {start.strftime('%Y-%m-%d')}")
            elif old_max:
                start = pd.Timestamp(old_max).normalize() + pd.Timedelta(days=1)
            else:
                start = (pd.Timestamp.today().normalize() - pd.DateOffset(years=int(default_years))).normalize()
            series, source = _load_series(spec, fred=fred, start=start)
            if series is None or series.empty or source is None:
                _log(f"macro {spec.series_id}: no new data")
                continue
            if old_max:
                series = series[series.index > pd.Timestamp(old_max).normalize()]
            rows = _macro_series_rows(spec, series, source)
            count = _upsert_macro_rows(conn, spec, rows, source)
            total += count
            _log(f"macro {spec.series_id}: candidate rows={count} source={source}")
    missing_rewrite_ids = rewrite_ids.difference({str(spec.series_id).upper() for spec in ALL_SPECS})
    if missing_rewrite_ids:
        _log(f"macro rewrite ignored unknown series: {', '.join(sorted(missing_rewrite_ids))}")
    _log(f"macro direct refresh wrote candidate rows={total}")
    return total


def upload_local_prices_to_remote(*, local_db: Path, overlap_days: int) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for local upload.")
    if not local_db.is_file():
        raise FileNotFoundError(f"Local S&P500 SQLite DB not found: {local_db}")
    with _connect_shared_prices_read_db() as remote, sqlite3.connect(local_db) as local:
        _ensure_remote_prices_schema(remote)
        old_max = _table_max_date(remote, "prices")
        query = """
            SELECT symbol, date, open, high, low, close, volume, adj_close, dividends, stock_splits
            FROM prices
        """
        params: list[object] = []
        if old_max:
            cutoff = _overlap_fetch_start_date("1900-01-01", old_max, overlap_days)
            query += " WHERE date >= ?"
            params.append(cutoff)
        query += " ORDER BY date, symbol"
        rows = [tuple(row) for row in local.execute(query, params).fetchall()]
        attempted = _insert_price_rows(remote, rows)
        market_cap_query = """
            SELECT market_cap, symbol, date
            FROM prices
            WHERE market_cap IS NOT NULL
        """
        market_cap_params: list[object] = []
        if old_max:
            cutoff = _overlap_fetch_start_date("1900-01-01", old_max, overlap_days)
            market_cap_query += " AND date >= ?"
            market_cap_params.append(cutoff)
        market_cap_rows = [tuple(row) for row in local.execute(market_cap_query, market_cap_params).fetchall()]
        _executemany_chunks(
            remote,
            """
            UPDATE prices
            SET market_cap = ?
            WHERE symbol = ? AND date = ?
            """,
            market_cap_rows,
        )
        _log(
            f"local S&P500 upload to {_remote_label()} old_max={old_max or '-'} "
            f"price_candidate_rows={attempted} market_cap_candidate_rows={len(market_cap_rows)}"
        )
        return attempted


def upload_local_fundamentals_to_remote(*, local_db: Path) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for local fundamentals upload.")
    if not local_db.is_file():
        raise FileNotFoundError(f"Local S&P500 SQLite DB not found: {local_db}")
    total = 0
    with _connect_shared_prices_read_db() as remote, sqlite3.connect(local_db) as local:
        _ensure_remote_prices_schema(remote)
        if _local_has_table(local, "fundamentals_snapshot"):
            rows = [
                tuple(row)
                for row in local.execute(
                    """
                    SELECT symbol, as_of_date, roe, per, pbr, source
                    FROM fundamentals_snapshot
                    """
                ).fetchall()
            ]
            total += _executemany_chunks(
                remote,
                """
                INSERT INTO fundamentals_snapshot(symbol, as_of_date, roe, per, pbr, source)
                VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(symbol) DO UPDATE SET
                    as_of_date=excluded.as_of_date,
                    roe=excluded.roe,
                    per=excluded.per,
                    pbr=excluded.pbr,
                    source=excluded.source,
                    updated_at=CURRENT_TIMESTAMP
                """,
                rows,
            )
            _log(f"local fundamentals_snapshot upload candidate rows={len(rows)}")
        if _local_has_table(local, "fundamentals_quarterly"):
            rows = [
                tuple(row)
                for row in local.execute(
                    """
                    SELECT
                        symbol, fiscal_date, filing_date, period_type, net_income, diluted_eps,
                        stockholders_equity, total_assets, total_debt, current_assets,
                        current_liabilities, operating_cash_flow, free_cash_flow, source
                    FROM fundamentals_quarterly
                    """
                ).fetchall()
            ]
            total += _executemany_chunks(
                remote,
                """
                INSERT INTO fundamentals_quarterly(
                    symbol, fiscal_date, filing_date, period_type, net_income, diluted_eps,
                    stockholders_equity, total_assets, total_debt, current_assets,
                    current_liabilities, operating_cash_flow, free_cash_flow, source
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(symbol, fiscal_date) DO UPDATE SET
                    filing_date=excluded.filing_date,
                    period_type=excluded.period_type,
                    net_income=excluded.net_income,
                    diluted_eps=excluded.diluted_eps,
                    stockholders_equity=excluded.stockholders_equity,
                    total_assets=excluded.total_assets,
                    total_debt=excluded.total_debt,
                    current_assets=excluded.current_assets,
                    current_liabilities=excluded.current_liabilities,
                    operating_cash_flow=excluded.operating_cash_flow,
                    free_cash_flow=excluded.free_cash_flow,
                    source=excluded.source,
                    updated_at=CURRENT_TIMESTAMP
                """,
                rows,
            )
            _log(f"local fundamentals_quarterly upload candidate rows={len(rows)}")
    return total


def upload_local_news_to_remote(*, local_db: Path, overlap_days: int) -> int:
    if not using_remote_shared_prices_db():
        raise RuntimeError("KEUMJ_SP500_DATABASE_URL or KEUMJ_SP500_SUPABASE_* must be set for local news upload.")
    if not local_db.is_file():
        raise FileNotFoundError(f"Local S&P500 SQLite DB not found: {local_db}")
    with _connect_shared_prices_read_db() as remote, sqlite3.connect(local_db) as local:
        _ensure_remote_prices_schema(remote)
        if not _local_has_table(local, "news_articles"):
            _log("local news_articles table not found; skipping news upload")
            return 0
        query = """
            SELECT ticker, publish_date, title, link, source, sentiment_score, analysis_status
            FROM news_articles
        """
        query += " ORDER BY publish_date, ticker, id"
        rows = [tuple(row) for row in local.execute(query).fetchall()]
        attempted = _executemany_chunks(
            remote,
            """
            INSERT INTO news_articles (ticker, publish_date, title, link, source, sentiment_score, analysis_status)
            SELECT ?, ?, ?, ?, ?, ?, ?
            WHERE NOT EXISTS (
                SELECT 1 FROM news_articles
                WHERE ticker = ? AND publish_date = ? AND link = ?
            )
            """,
            [(*row, row[0], row[1], row[3]) for row in rows],
        )
        _log(
            f"local news upload to {_remote_label()} local_candidate_rows={attempted} "
            "mode=all-local-dedup-by-ticker-publish-date-link"
        )
        return attempted


def upload_local_macro_to_remote(*, local_db: Path) -> int:
    if not using_remote_macro_db():
        raise RuntimeError("KEUMJ_MACRO_DATABASE_URL or KEUMJ_MACRO_SUPABASE_* must be set for local upload.")
    if not local_db.is_file():
        raise FileNotFoundError(f"Local macro SQLite DB not found: {local_db}")
    total = 0
    with _connect_macro_read_db() as remote, sqlite3.connect(local_db) as local:
        _ensure_remote_macro_schema(remote)
        for spec in ALL_SPECS:
            old_max = _table_max_date(remote, "macro_series", where_sql="series_id = ?", params=(spec.series_id,))
            query = """
                SELECT series_id, date, value, dataset, frequency, source
                FROM macro_series
                WHERE series_id = ?
            """
            params: list[object] = [spec.series_id]
            if old_max:
                query += " AND date > ?"
                params.append(old_max)
            query += " ORDER BY date"
            rows = [tuple(row) for row in local.execute(query, params).fetchall()]
            source = str(rows[-1][5]) if rows else "local_sqlite"
            total += _upsert_macro_rows(remote, spec, rows, source)
        _log(f"local macro upload to {_remote_label()} candidate rows={total}")
        return total


upload_local_prices_to_turso = upload_local_prices_to_remote
upload_local_fundamentals_to_turso = upload_local_fundamentals_to_remote
upload_local_news_to_turso = upload_local_news_to_remote
upload_local_macro_to_turso = upload_local_macro_to_remote


def refresh_local_databases(args: argparse.Namespace) -> None:
    local_sp500_db = Path(args.local_sp500_db)
    local_macro_db = Path(args.local_macro_db)

    _log(f"STAGE 1/2 local SQLite incremental refresh started: target={args.target}")
    if args.target in {"all", "sp500", "prices"}:
        _log(f"STAGE 1/2 local S&P500 price refresh -> {local_sp500_db}")
        refresh_sp500_shared_prices(
            data_dir=DEFAULT_DATA_DIR,
            shared_db_root=local_sp500_db.parent if local_sp500_db.name else DEFAULT_SHARED_DB_ROOT,
            symbols_csv=Path(args.symbols_csv),
            start_date=str(args.start_date),
            chunk_size=int(args.chunk_size),
            provider=str(args.provider),
            pause_seconds=float(args.pause_seconds),
        )

    if args.target in {"all", "sp500", "fundamentals"}:
        _log(f"STAGE 1/2 local fundamentals refresh -> {local_sp500_db}")
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "pipeline_common.refresh_shared_quarterly_fundamentals",
                "--db-path",
                str(local_sp500_db),
                "--limit-per-symbol",
                str(int(args.fundamental_limit_per_symbol)),
                "--pause-seconds",
                str(float(args.pause_seconds)),
            ],
            cwd=str(ROOT),
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(f"local fundamentals refresh failed with exit code {result.returncode}")

    if args.target in {"all", "sp500", "news"}:
        _log(f"STAGE 1/2 local news refresh -> {local_sp500_db}")
        sync_sp500_news_articles(
            backfill_days=int(args.news_backfill_days),
            overlap_days=int(args.overlap_days),
            max_items=int(args.news_max_items),
            timeout=int(args.news_timeout),
            components_csv=Path(args.symbols_csv),
            db_path=local_sp500_db,
        )

    if args.target in {"all", "macro"}:
        _log(f"STAGE 1/2 local macro refresh -> {local_macro_db}")
        refresh_macro_prices(
            db_path=local_macro_db,
            years=int(args.macro_years),
            require_fred=False,
        )
    _log(f"STAGE 1/2 local SQLite incremental refresh finished: target={args.target}")


def _record_run(status: str, mode: str, counts: JobCounts, message: str) -> None:
    targets = []
    if using_remote_shared_prices_db():
        targets.append(("sp500", _connect_shared_prices_read_db, _ensure_remote_prices_schema))
    if using_remote_macro_db():
        targets.append(("macro", _connect_macro_read_db, _ensure_remote_macro_schema))
    for name, connect, ensure in targets:
        try:
            with connect() as conn:
                ensure(conn)
                conn.execute(
                    """
                    INSERT INTO refresh_runs(
                        job_name, mode, status, finished_at,
                        price_rows, fundamental_rows, news_rows, macro_rows, message
                    )
                    VALUES (?, ?, ?, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?)
                    """,
                    (
                        name,
                        mode,
                        status,
                        int(counts.price_rows),
                        int(counts.fundamental_rows),
                        int(counts.news_rows),
                        int(counts.macro_rows),
                        message[:1000],
                    ),
                )
                conn.commit()
        except Exception as exc:
            _log(f"failed to record refresh run in {name}: {type(exc).__name__}: {exc}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Incrementally refresh remote calculation DBs.")
    parser.add_argument("--mode", choices=["direct", "upload-local", "local-then-upload"], default="direct")
    parser.add_argument("--target", choices=["all", "sp500", "prices", "fundamentals", "news", "macro"], default="all")
    parser.add_argument("--symbols-csv", default=str(DEFAULT_COMPONENTS_CSV))
    parser.add_argument("--start-date", default=DEFAULT_START_DATE)
    parser.add_argument("--chunk-size", type=int, default=50)
    parser.add_argument("--provider", choices=["auto", "yfinance", "fdr"], default="auto")
    parser.add_argument("--pause-seconds", type=float, default=0.0)
    parser.add_argument("--overlap-days", type=int, default=3, help="Re-read recent days to fill partial failed runs.")
    parser.add_argument("--fundamental-limit-per-symbol", type=int, default=4)
    parser.add_argument("--news-backfill-days", type=int, default=DEFAULT_BACKFILL_DAYS)
    parser.add_argument("--news-max-items", type=int, default=DEFAULT_MAX_ITEMS)
    parser.add_argument("--news-timeout", type=int, default=8)
    parser.add_argument("--macro-years", type=int, default=5)
    parser.add_argument(
        "--macro-rewrite-series",
        default="",
        help="Comma-separated macro series IDs to delete and rebuild for the --macro-years window, e.g. DXY.",
    )
    parser.add_argument("--local-sp500-db", default=str(shared_prices_sqlite_path()))
    parser.add_argument("--local-macro-db", default=str(macro_db_path()))
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    os.environ["KEUMJ_TURSO_EMBEDDED_REPLICA"] = "false"
    try:
        price_rows = 0
        fundamental_rows = 0
        news_rows = 0
        macro_rows = 0
        if args.mode == "direct":
            if args.target in {"all", "sp500", "prices"}:
                price_rows = refresh_prices_direct(
                    symbols_csv=Path(args.symbols_csv),
                    start_date=str(args.start_date),
                    chunk_size=int(args.chunk_size),
                    provider=str(args.provider),
                    pause_seconds=float(args.pause_seconds),
                    overlap_days=int(args.overlap_days),
                )
            if args.target in {"all", "sp500", "fundamentals"}:
                fundamental_rows = refresh_fundamentals_direct(
                    symbols_csv=Path(args.symbols_csv),
                    limit_per_symbol=int(args.fundamental_limit_per_symbol),
                    pause_seconds=float(args.pause_seconds),
                )
                fundamental_rows += refresh_fundamentals_snapshot_direct(
                    symbols_csv=Path(args.symbols_csv),
                    limit_per_symbol=int(args.fundamental_limit_per_symbol),
                )
            if args.target in {"all", "sp500", "news"}:
                news_rows = refresh_news_direct(
                    symbols_csv=Path(args.symbols_csv),
                    backfill_days=int(args.news_backfill_days),
                    overlap_days=int(args.overlap_days),
                    max_items=int(args.news_max_items),
                    timeout=int(args.news_timeout),
                )
            if args.target in {"all", "macro"}:
                macro_rows = refresh_macro_direct(
                    default_years=int(args.macro_years),
                    rewrite_series=_parse_series_ids(str(args.macro_rewrite_series)),
                )
        else:
            if args.mode == "local-then-upload":
                refresh_local_databases(args)
            _log(f"STAGE 2/2 {_remote_label()} incremental upload started: target={args.target}")
            if args.target in {"all", "sp500", "prices"}:
                price_rows = upload_local_prices_to_remote(
                    local_db=Path(args.local_sp500_db),
                    overlap_days=int(args.overlap_days),
                )
            if args.target in {"all", "sp500", "fundamentals"}:
                fundamental_rows = upload_local_fundamentals_to_remote(local_db=Path(args.local_sp500_db))
            if args.target in {"all", "sp500", "news"}:
                news_rows = upload_local_news_to_remote(
                    local_db=Path(args.local_sp500_db),
                    overlap_days=int(args.overlap_days),
                )
            if args.target in {"all", "macro"}:
                macro_rows = upload_local_macro_to_remote(local_db=Path(args.local_macro_db))
            _log(f"STAGE 2/2 {_remote_label()} incremental upload finished: target={args.target}")
        counts = JobCounts(
            price_rows=price_rows,
            fundamental_rows=fundamental_rows,
            news_rows=news_rows,
            macro_rows=macro_rows,
        )
        _record_run("ok", str(args.mode), counts, "completed")
        _log(
            f"SUMMARY status=ok mode={args.mode} price_rows={price_rows} "
            f"fundamental_rows={fundamental_rows} news_rows={news_rows} macro_rows={macro_rows}"
        )
        return 0
    except Exception as exc:
        counts = JobCounts()
        _record_run("error", str(args.mode), counts, f"{type(exc).__name__}: {exc}")
        _log(f"SUMMARY status=error mode={args.mode} error_type={type(exc).__name__}")
        print(f"Refresh failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
